USE_LOGS = False

# RANDOM WALLETS MODE
RANDOM_WALLET = True  # True or False

SLEEP_FROM = 65  # Second
SLEEP_TO = 100  # Second

QUANTITY_THREADS = 4

THREAD_SLEEP_FROM = 300  # Second
THREAD_SLEEP_TO = 600  # Second

# PROXY MODE
USE_PROXY = True

# RETRY MODE
RETRY_COUNT = 10

GWEI = 1.1
GAS_MULTIPLIER = 1.03
